### ISSUE TITLE
Building fails

### ISSUE THREAD

**Issue by z3ntu** [keesj/alps-fairphone-gpl#2]
```
fs/file_table.c: In function 'get_empty_filp':
fs/file_table.c:36:20: error: inlining failed in call to always_inline 'fd_show_open_files': function body not available
 extern inline void fd_show_open_files(pid_t pid, struct files_struct *files, struct fdtable *fdt);
                    ^
fs/file_table.c:160:36: error: called from here
                  fd_show_open_files(pid, files, fdt);
                                    ^
scripts/Makefile.build:307: recipe for target 'fs/file_table.o' failed
make[1]: *** [fs/file_table.o] Error 1
Makefile:967: recipe for target 'fs' failed
make: *** [fs] Error 2
```

My toolchain path is /home/luca/Android/Sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.8/prebuilt/linux-x86_64/bin

**Comment by z3ntu** [comment]
Okay, you HAVE to use toolchain version 4.6 (not 4.7 or 4.8), I used `git clone https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.6`

I will write that down somewhere in this Repo (probably the Wiki)

**Comment by nicksspirit** [comment]
You should check the file that your compiler points to as causing the
error. Plus are you building for KitKat kernel?

**Comment by z3ntu** [comment]
Compiling works with toolchain version 4.6

> Plus are you building for KitKat kernel?

I don't know... I was just following the instructions in the wiki, I also have like 0 experience with Android kernel/custom roms/whatever. the FP1u was my first Android phone/device so I also have no other device to try anything^^

**Comment by keesj** [comment]
Closing this issue as the build works with the advertised toolchain.  I don't think upgrading the toolchain at this point is worth the effort.
